// <auto-generated />
using System;
using CareConnect.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareConnect.Services.Migrations
{
    [DbContext(typeof(CareConnectContext))]
    [Migration("20251001125731_NullableItemIdInPayment")]
    partial class NullableItemIdInPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareConnect.Services.Database.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AttendanceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceStatusID");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeAvailabilityId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeAvailabilityID");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("NOTE");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA2BDE101EB");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("EmployeeAvailabilityId");

                    b.HasIndex("ClientId", "ChildId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.AttendanceStatus", b =>
                {
                    b.Property<int>("AttendanceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceStatusId"));

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceStatusId")
                        .HasName("PK__Attendan__7696A71507991871");

                    b.ToTable("AttendanceStatus", (string)null);
                });

            modelBuilder.Entity("CareConnect.Services.Database.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChildID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ChildId")
                        .HasName("PK__Children__BEFA0736EA5ECDD8");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ChildrenDiagnosis", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("ChildID");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int")
                        .HasColumnName("DiagnosisID");

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("ChildId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("ChildrenDiagnoses");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmploymentStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ClientsChild", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("ChildID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ClientId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("ClientsChildren");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiagnosisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DiagnosisId")
                        .HasName("PK__Diagnose__0C54CB93F48849F6");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("int")
                        .HasColumnName("QualificationID");

                    b.HasKey("EmployeeId");

                    b.HasIndex("QualificationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CareConnect.Services.Database.EmployeeAvailability", b =>
                {
                    b.Property<int>("EmployeeAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeAvailabilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAvailabilityId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeAvailabilityId")
                        .HasName("PK__Employee__A9E4B8771C174821");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EmployeeAvailability", (string)null);
                });

            modelBuilder.Entity("CareConnect.Services.Database.EmployeePayHistory", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("RateChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EmployeeId", "RateChangeDate");

                    b.ToTable("EmployeePayHistory", (string)null);
                });

            modelBuilder.Entity("CareConnect.Services.Database.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfessionalTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__9D010B7B6EBA19E2");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MemberId", "JoinedDate");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int>("AttendanceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("AttendanceStatusID");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int")
                        .HasColumnName("WorkshopID");

                    b.HasKey("ParticipantId");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("ChildId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("ChildID");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("EmployeeAvailabilityId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PaymentPurposeId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A581C157F0D");

                    b.HasIndex("PaymentPurposeId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.PaymentPurpose", b =>
                {
                    b.Property<int>("PaymentPurposeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentPurposeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentPurposeId"));

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentPurposeId")
                        .HasName("PK__PaymentP__847171664C3B3572");

                    b.ToTable("PaymentPurposes");
                });

            modelBuilder.Entity("CareConnect.Services.Database.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentStatusId")
                        .HasName("PK__PaymentS__34F8AC1F8C1BD45C");

                    b.ToTable("PaymentStatus", (string)null);
                });

            modelBuilder.Entity("CareConnect.Services.Database.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PermissionId")
                        .HasName("PK__Permissi__EFA6FB2FD9DF3E33");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QualificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualificationId"));

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcurementYear")
                        .HasColumnType("datetime");

                    b.HasKey("QualificationId")
                        .HasName("PK__Qualific__C95C128ACC47C0D4");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AE38912645");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A1FCEAE44");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MemberPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB0EAAE76A19D");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int")
                        .HasColumnName("WorkshopID");

                    b.HasKey("SessionId")
                        .HasName("PK__Sessions__C9F49270A1B7D6A1");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CareConnect.Services.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC3071E9A0");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareConnect.Services.Database.UsersRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Workshop", b =>
                {
                    b.Property<int>("WorkshopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkshopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal?>("MemberPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Participants")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkshopType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkshopId")
                        .HasName("PK__Workshop__7A008C2A3EFF4987");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK__RolePerm__6400A1A8026A7CAE");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("CareConnect.Services.Database.Appointment", b =>
                {
                    b.HasOne("CareConnect.Services.Database.AttendanceStatus", "AttendanceStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("AttendanceStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_AttendanceStatus");

                    b.HasOne("CareConnect.Services.Database.EmployeeAvailability", "EmployeeAvailability")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeAvailabilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_EmployeeAvailability");

                    b.HasOne("CareConnect.Services.Database.ClientsChild", "ClientsChild")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_ClientsChildren");

                    b.Navigation("AttendanceStatus");

                    b.Navigation("ClientsChild");

                    b.Navigation("EmployeeAvailability");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ChildrenDiagnosis", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Child", "Child")
                        .WithMany("ChildrenDiagnoses")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("FK_ChildrenDiagnoses_Children");

                    b.HasOne("CareConnect.Services.Database.Diagnosis", "Diagnosis")
                        .WithMany("ChildrenDiagnoses")
                        .HasForeignKey("DiagnosisId")
                        .IsRequired()
                        .HasConstraintName("FK_ChildrenDiagnoses_Diagnoses");

                    b.Navigation("Child");

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Client", b =>
                {
                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("CareConnect.Services.Database.Client", "ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_Clients_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ClientsChild", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Child", "Child")
                        .WithMany("ClientsChildren")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientsChildren_Children");

                    b.HasOne("CareConnect.Services.Database.Client", "Client")
                        .WithMany("ClientsChildren")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientsChildren_Clients");

                    b.Navigation("Child");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Employee", b =>
                {
                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("CareConnect.Services.Database.Employee", "EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Users");

                    b.HasOne("CareConnect.Services.Database.Qualification", "Qualification")
                        .WithMany("Employees")
                        .HasForeignKey("QualificationId")
                        .HasConstraintName("FK_Employees_Qualifications");

                    b.Navigation("Qualification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareConnect.Services.Database.EmployeeAvailability", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Employee", "Employee")
                        .WithMany("EmployeeAvailabilities")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeAvailability_Employees");

                    b.HasOne("CareConnect.Services.Database.Service", "Service")
                        .WithMany("EmployeeAvailabilities")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_EmployeeAvailability_Services");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CareConnect.Services.Database.EmployeePayHistory", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Employee", "Employee")
                        .WithMany("EmployeePayHistories")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeePayHistory_Users");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Enrollment", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Child", "Child")
                        .WithMany("Enrollments")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CareConnect.Services.Database.Client", "Client")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareConnect.Services.Database.Workshop", "Workshop")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Client");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Member", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Client", "Client")
                        .WithMany("Members")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Members_Clients");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Participant", b =>
                {
                    b.HasOne("CareConnect.Services.Database.AttendanceStatus", "AttendanceStatus")
                        .WithMany("Participants")
                        .HasForeignKey("AttendanceStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_AttendanceStatus");

                    b.HasOne("CareConnect.Services.Database.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId");

                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_Users");

                    b.HasOne("CareConnect.Services.Database.Workshop", "Workshop")
                        .WithMany("ParticipantsNavigation")
                        .HasForeignKey("WorkshopId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_Workshops");

                    b.Navigation("AttendanceStatus");

                    b.Navigation("Child");

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Payment", b =>
                {
                    b.HasOne("CareConnect.Services.Database.PaymentPurpose", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentPurposeId");

                    b.HasOne("CareConnect.Services.Database.PaymentStatus", null)
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId");

                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Review", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Employee", "Employee")
                        .WithMany("Reviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Employees");

                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Service", b =>
                {
                    b.HasOne("CareConnect.Services.Database.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_ServiceTypes");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Session", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Employee", "Employee")
                        .WithMany("Sessions")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Sessions_Employees");

                    b.HasOne("CareConnect.Services.Database.Instructor", "Instructor")
                        .WithMany("Sessions")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_Sessions_Instructors");

                    b.HasOne("CareConnect.Services.Database.Workshop", "Workshop")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkshopId")
                        .IsRequired()
                        .HasConstraintName("FK_Sessions_Workshops");

                    b.Navigation("Employee");

                    b.Navigation("Instructor");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CareConnect.Services.Database.UsersRole", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Role", "Role")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UsersRoles_Roles");

                    b.HasOne("CareConnect.Services.Database.User", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UsersRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("CareConnect.Services.Database.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__Permi__3F115E1A");

                    b.HasOne("CareConnect.Services.Database.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__RoleI__3E1D39E1");
                });

            modelBuilder.Entity("CareConnect.Services.Database.AttendanceStatus", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Child", b =>
                {
                    b.Navigation("ChildrenDiagnoses");

                    b.Navigation("ClientsChildren");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Client", b =>
                {
                    b.Navigation("ClientsChildren");

                    b.Navigation("Enrollments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ClientsChild", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Diagnosis", b =>
                {
                    b.Navigation("ChildrenDiagnoses");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Employee", b =>
                {
                    b.Navigation("EmployeeAvailabilities");

                    b.Navigation("EmployeePayHistories");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CareConnect.Services.Database.EmployeeAvailability", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Instructor", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CareConnect.Services.Database.PaymentPurpose", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Qualification", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Role", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Service", b =>
                {
                    b.Navigation("EmployeeAvailabilities");
                });

            modelBuilder.Entity("CareConnect.Services.Database.ServiceType", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CareConnect.Services.Database.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Participants");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("CareConnect.Services.Database.Workshop", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ParticipantsNavigation");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
